from flask import Blueprint, jsonify, request
from flask import Blueprint, render_template, request
from .utils.brewfather import fetch_inventory, fetch_recipes, fetch_specific_inventory
from .utils.bjcp import fetch_bjcp_styles
from .utils.openai_integration import generate_recipe, suggest_beer_styles

from app.utils.brewfather import fetch_inventory, fetch_recipes, fetch_specific_inventory
from app.utils.bjcp import fetch_bjcp_styles
from app.utils.openai_integration import generate_recipe, suggest_beer_styles


# Definiera Blueprint
main = Blueprint('main', __name__)

@main.route('/api')
def index():
    return jsonify({"message": "Välkommen till BrewBuddy API!"})

@main.route('/brewfather/inventory')
def get_inventory():
    return jsonify(fetch_inventory())

@main.route('/brewfather/inventory/fermentables')
def get_fermentables():
    return jsonify(fetch_specific_inventory("fermentables"))

@main.route('/brewfather/inventory/hops')
def get_hops():
    return jsonify(fetch_specific_inventory("hops"))

@main.route('/brewfather/inventory/yeasts')
def get_yeasts():
    return jsonify(fetch_specific_inventory("yeasts"))

@main.route('/brewfather/recipes')
def get_recipes():
    return jsonify(fetch_recipes())

@main.route('/bjcp-styles')
def get_bjcp_styles():
    return jsonify(fetch_bjcp_styles())

@main.route('/generate-recipe', methods=['POST'])
def generate_recipe_endpoint():
    data = request.json
    if data.get("finalize"):
        # Skapa det slutliga receptet baserat på konversationen
        return jsonify({"recipe": "Final recipe generated by ChatGPT."})
    else:
        # Hantera meddelanden i chatten
        user_input = data.get("user_input")
        response = generate_chat_response(user_input)
        return jsonify({"response": response})



@main.route('/', methods=['GET', 'POST'])
def home():
    recipe = None
    if request.method == 'POST':
        # Hämta data från formuläret
        bjcp_style = {
            "name": request.form.get('name'),
            "description": request.form.get('description')
        }
        inventory = {
            "fermentables": [{"name": f.strip()} for f in request.form.get('fermentables').split(',')],
            "hops": [{"name": h.strip()} for h in request.form.get('hops').split(',')],
            "yeasts": [{"name": y.strip()} for y in request.form.get('yeasts').split(',')]
        }

        # Generera recept
        recipe = generate_recipe(bjcp_style, inventory)

    return render_template('index.html', recipe=recipe)

@api.route('/suggest_styles', methods=['POST'])
def suggest_styles():
    """
    Endpoint för att få ölstilsförslag från ChatGPT.
    """
    data = request.get_json()
    ingredients = data.get('ingredients', [])

    if not ingredients:
        return jsonify({"error": "Inga ingredienser angivna"}), 400

    suggestions = suggest_beer_styles(ingredients)
    return jsonify({"suggestions": suggestions}), 200
